version: '3.9'

services:
  rabbitmq:
    image: masstransitdemo/rabbitmq:1
    ports:
      - 5672:5672
      - 8080:15672
  prometheus:
    image: ubuntu/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/opt/prometheus/prometheus.yml