version: '3.9'

services:
  rabbitmq:
    image: masstransitdemo/rabbitmq:1
    ports:
      - 5672:5672
      - 8080:15672
  prometheus:
    image: ubuntu/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  # webapi:
  #   image: masstransitdemo/webapi:1
  #   ports:
  #     - 8000:80
  # consumerrunner:
  #   image: masstransitdemo/consumerrunner:1
